git push -u origin mainname: Update PR Title If Target Branch Is A Version Branch

on:
  pull_request_target:
    types: [opened, edited]
    branches:
      - "release_**"


jobs:
  update-title:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: Update PR title
        run: |
          PR_NUMBER=${{ github.event.pull_request.number }}
          TARGET_BRANCH=$(gh pr view $PR_NUMBER --json baseRefName -q .baseRefName)
          PR_TITLE=$(gh pr view $PR_NUMBER --json title -q .title)
          VERSION=$(echo $TARGET_BRANCH | grep -oP '\d+\.\d+')
          if [[ -n "$VERSION" && ! "$PR_TITLE" =~ ^\[$VERSION\] ]]; then
            NEW_TITLE="[$VERSION] $PR_TITLE"
            gh pr edit $PR_NUMBER --title "$NEW_TITLE"
          fi
