name: Run Testing Copied Histories

on:
  workflow_dispatch:
    inputs:
      starts_with:
        description: 'Search histories base on this prefix in name'
        required: false
        default: ''
        type: string
      history_id:
        description: 'Find history by this ID'
        required: false
        default: ''
        type: string
      since_date:
        description: 'Only process items updated on or after this date (format: YYYY-MM-DD)'
        required: false
        default: '2025-01-01'

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
            python-version: '3.12'

      - name: Install dependencies
        run: |
            pip install -r requirements_copied_histories.txt

      - name: Run testing_copied_histories
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            STARTS_WITH: ${{ github.event.inputs.starts_with }}
            HISTORY_ID: ${{ github.event.inputs.history_id }}
            SINCE_DATE: ${{ github.event.inputs.since_date }}
            GALAXY_API_KEY: ${{ secrets.GALAXY_API_KEY }}
            GITHUB_REPO: ${{ github.repository }}
        run: |
            python testing_copied_histories.py