name: Update 

on:
  pull_request_target:
    types: [opened, edited, reopened]

jobs:
  update-title:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: "main"
          token: ${{ secrets.GITHUB_TOKEN }}
      - run: mkdir markdown
      - run: echo "Hello World" > markdown/hello.md
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          file_pattern: '*.md'
          disable_globbing: true