name: Set environment variables from plugins.yml

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Extract secrets from plugins.yml and set environment variables
        run: |
          python -m pip install --upgrade pip
          python -m pip install pyyaml
          python set_env.py

      - name: Verify environment variables
        run: |
          cat $GITHUB_ENV
