name: Update

on:
  pull_request_target:

env:
  GALAXY_FORK: galaxyproject
  GALAXY_BRANCH: release_24.1
  MAX_CHUNKS: 4
  CMEMS_PASSWORD: ${{ secrets.CMEMS_PASSWORD }}
  CMEMS_USERNAME: ${{ secrets.CMEMS_USERNAME }}
  MAX_FILE_SIZE: 1M

jobs:
  example_job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Run Python Script
        run: |
          python test.py
