name: Test2

on:
  pull_request_target:
    branches: [main]
    types: [opened, synchronize, reopened, closed]
    paths:
      - "posts/**"

  workflow_dispatch:
    inputs:
      pr_number:
        description: "The number of the pull request to create preview for"
        required: true
        type: number

jobs:
  test2:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Run scriot
        env:
          PR_NUMBER: ${{ github.event.inputs.pr_number || github.event.number }}
          ACTION_TYPE: ${{ github.event.action }}
          MERGED: ${{ github.event.pull_request.merged }}
          EVENT_NAME: ${{ github.event_name }}
        run: python -u test2.py